name: build dev docker image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Get the current version from VERSION_DEV
        id: get_version
        run: |
          VERSION=$(cat VERSION_DEV)
          echo "Current version: $VERSION"
          echo "::set-output name=current_version::$VERSION"

      - name: Increment the version
        id: increment_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.current_version }}
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > VERSION_DEV
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Commit and push the new version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION_DEV
          git commit -m "Increment VERSION_DEV to ${{ steps.increment_version.outputs.new_version }}"
          git push origin HEAD:dev

      - name: Build the Docker image
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
          docker build . --file Dockerfile --tag blockchain-insights/dev:v$NEW_VERSION

      # Add steps for Docker login and push if needed

      - name: Push new tag
        if: github.ref == 'refs/heads/dev'
        run: |
          NEW_TAG=${{ steps.increment-tag.outputs.incremented_tag }}
          git tag $NEW_TAG
          git push origin $NEW_TAG
